# Generated by Django 5.1.4 on 2025-01-31 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='رقم البطاقة يجب أن يكون بين 13 و 19 رقمًا.', regex='^\\d{13,19}$')], verbose_name='رقم البطاقة')),
                ('expiry_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='شهر الانتهاء')),
                ('expiry_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)], verbose_name='سنة الانتهاء')),
                ('security_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='يجب أن يكون رمز الأمان مكونًا من 3 أو 4 أرقام.', regex='^\\d{3,4}$')], verbose_name='رمز الأمان')),
                ('card_holder_name', models.CharField(max_length=255, verbose_name='اسم حامل البطاقة')),
            ],
        ),
    ]
