# Generated by Django 5.1.4 on 2025-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='encrypted_card_number',
            field=models.BinaryField(default=b''),
        ),
    ]
