# Generated by Django 5.1.4 on 2025-01-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Aboutus',
            },
        ),
    ]
