# Generated by Django 5.1.4 on 2025-01-27 22:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSource',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'AdsSource',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('directorate_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=40)),
                ('serial_group', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Feature',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('rent_or_sell', models.IntegerField(blank=True, choices=[(1, 'Rent'), (2, 'Sell')], null=True)),
            ],
            options={
                'db_table': 'RealEstate',
            },
        ),
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'RealEstateType',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Services_details',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Services_details',
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('phone_num', models.CharField(max_length=13)),
                ('status', models.BooleanField(default=False)),
                ('ID_number', models.IntegerField(max_length=11)),
                ('user_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertiser',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('upddate_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'قيد الانتظار'), (2, 'قيد المراجعة'), (3, 'منشورة'), (4, 'مرفوضة'), (5, 'محذوفة')], default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.adssource')),
                ('advertiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.advertiser')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Advertiser.area')),
                ('RealEstate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Advertiser.realestate')),
                ('Service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Advertiser.service')),
            ],
            options={
                'db_table': 'Advertisement',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Advertiser.feature')),
                ('realEstate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.realestate')),
            ],
            options={
                'db_table': ' RealEstate_Feature',
            },
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d')),
                ('RealEstate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Advertiser.realestate')),
            ],
            options={
                'db_table': 'RealEstateImage',
            },
        ),
        migrations.AddField(
            model_name='realestate',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Advertiser.realestatetype'),
        ),
        migrations.AddField(
            model_name='service',
            name='Services_details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Advertiser.services_details'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('advertisement', 'user')},
            },
        ),
    ]
