# Generated by Django 5.1.4 on 2025-02-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0005_alter_advertiser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.advertisement'),
        ),
    ]
