# Generated by Django 5.1.4 on 2025-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0006_alter_rating_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adrecommendation',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='adrecommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_advertiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='AdRecommendation',
        ),
    ]
